"""schema inicial

Revision ID: f43b99e177a7
Revises: 
Create Date: 2026-08-07 10:10:41.805071
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f43b99e177a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_eventos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hash_proprio', sa.String(length=64), nullable=False),
    sa.Column('hash_anterior', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.String(length=35), nullable=False),
    sa.Column('versao_sistema', sa.String(length=20), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('lancamento_id', sa.String(length=36), nullable=True),
    sa.Column('documento_id', sa.String(length=36), nullable=True),
    sa.Column('documento_hash', sa.String(length=64), nullable=True),
    sa.Column('campo_alterado', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('versao_regra', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_proprio')
    )
    op.create_index(op.f('ix_audit_eventos_documento_id'), 'audit_eventos', ['documento_id'], unique=False)
    op.create_index(op.f('ix_audit_eventos_empresa_id'), 'audit_eventos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_audit_eventos_lancamento_id'), 'audit_eventos', ['lancamento_id'], unique=False)
    op.create_index(op.f('ix_audit_eventos_timestamp'), 'audit_eventos', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_eventos_tipo'), 'audit_eventos', ['tipo'], unique=False)
    op.create_table('centros_custo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_centro_custo_empresa_codigo')
    )
    op.create_index(op.f('ix_centros_custo_empresa_id'), 'centros_custo', ['empresa_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fonte_extracao', sa.String(length=30), nullable=False),
    sa.Column('cnpj_emitente', sa.String(length=14), nullable=True),
    sa.Column('nome_emitente', sa.String(length=300), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_processamento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_desconto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('cfop', sa.String(length=10), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=20), nullable=True),
    sa.Column('metadados_nfe', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('confidence_minima', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('precisa_revisao', sa.Boolean(), nullable=False),
    sa.Column('motivo_revisao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'hash_sha256', name='uq_documento_hash_empresa')
    )
    op.create_index(op.f('ix_documentos_empresa_id'), 'documentos', ['empresa_id'], unique=False)
    op.create_table('periodos_contabeis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fechado_por', sa.String(length=100), nullable=True),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'ano', 'mes', name='uq_periodo_empresa_competencia')
    )
    op.create_index(op.f('ix_periodos_contabeis_empresa_id'), 'periodos_contabeis', ['empresa_id'], unique=False)
    op.create_table('lancamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('documento_id', sa.String(length=36), nullable=True),
    sa.Column('fornecedor_id', sa.String(length=36), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('data_competencia', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('historico_padronizado', sa.String(length=200), nullable=True),
    sa.Column('e_parcelado', sa.Boolean(), nullable=False),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('lancamento_pai_id', sa.String(length=36), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('metodo_classificacao', sa.String(length=50), nullable=True),
    sa.Column('regra_aplicada_id', sa.String(length=36), nullable=True),
    sa.Column('versao_regra', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nivel_aprovacao', sa.String(length=20), nullable=True),
    sa.Column('pre_aprovado', sa.Boolean(), nullable=False),
    sa.Column('aprovado_por_1', sa.String(length=100), nullable=True),
    sa.Column('aprovado_em_1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprovado_por_2', sa.String(length=100), nullable=True),
    sa.Column('aprovado_em_2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guid_gnucash', sa.String(length=36), nullable=True),
    sa.Column('exportado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_data_lancamento'), 'lancamentos', ['data_lancamento'], unique=False)
    op.create_index(op.f('ix_lancamentos_documento_id'), 'lancamentos', ['documento_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_empresa_id'), 'lancamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_status'), 'lancamentos', ['status'], unique=False)
    op.create_table('splits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lancamento_id', sa.String(length=36), nullable=False),
    sa.Column('conta_codigo', sa.String(length=20), nullable=False),
    sa.Column('natureza', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('centro_custo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_splits_lancamento_id'), 'splits', ['lancamento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_splits_lancamento_id'), table_name='splits')
    op.drop_table('splits')
    op.drop_index(op.f('ix_lancamentos_status'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_empresa_id'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_documento_id'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_data_lancamento'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_periodos_contabeis_empresa_id'), table_name='periodos_contabeis')
    op.drop_table('periodos_contabeis')
    op.drop_index(op.f('ix_documentos_empresa_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_centros_custo_empresa_id'), table_name='centros_custo')
    op.drop_table('centros_custo')
    op.drop_index(op.f('ix_audit_eventos_tipo'), table_name='audit_eventos')
    op.drop_index(op.f('ix_audit_eventos_timestamp'), table_name='audit_eventos')
    op.drop_index(op.f('ix_audit_eventos_lancamento_id'), table_name='audit_eventos')
    op.drop_index(op.f('ix_audit_eventos_empresa_id'), table_name='audit_eventos')
    op.drop_index(op.f('ix_audit_eventos_documento_id'), table_name='audit_eventos')
    op.drop_table('audit_eventos')
    # ### end Alembic commands ###
